volumes:
  snort_log:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=1g,uid=1000
  snort_data:

services:
  snort:
    image: mfscy/snort-base:3.3.4.0-debian-12.6
    restart: unless-stopped
    network_mode: host
    environment:
      SNORT_OINKCODE:
      NETWORK_INTERFACE: eth0
      DOWNLOAD_RULES: false
      SNORT_COMPRESSED_RULES_FILE_PATH:
      COMMUNITY_RULESET: false
      REGISTERED_RULESET: false
      LIGHTSPD_RULESET: false
      SNORT_BLOCKLIST: false
      ET_BLOCKLIST: false
      BLOCKLIST_URLS:
      IPS_POLICY: balanced
    volumes:
      - snort_log:/var/log/snort:rw
      - snort_data:/usr/local/etc/snort3
      - ./rules:/tmp/rules
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        max_attempts: 3
        delay: 10s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 512M


###########################
#         Note            #
###########################
# String/text `<machine-id>` will be replaced with content from /etc/machine-id
# String/text `<sensor-id>` will be replaced with content from SENSOR_ID env var
#

  snort-parser:
    image: mfscy/snort3-parser:2
    restart: unless-stopped
    command: "client -v"
    depends_on:
      - snort
    environment:
      MES_CLIENT_FILE: /var/log/snort/alert_json.txt
      MES_CLIENT_SERVER: 172.17.0.1
      MES_CLIENT_PORT: 50051
      MES_CLIENT_INSECURE: "true"
      MES_CLIENT_SENSOR_ID: 
      MES_CLIENT_INTERVAL: 1s
      MES_CLIENT_MAX_CLIENTS: 10
      MES_SERVER_MAX_MESSAGE_SIZE: 1024
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - snort_log:/var/log/snort:rw
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        max_attempts: 3
        delay: 10s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 512M
